var word_data = {
    data: {
        words: {
            categories: {
                movies: {
                    name: "Movies",
                    words: [
                        "Zootopia",
                        "Little Mermaid",
                        "Toy Story",
                        "Beauty and the Beast",
                        "Aladdin",
                        "The Little Rascals",
                        "Matilda",
                        "Shrek",
                        "The Incredibles",
                        "Cars",
                        "Happy Feet",
                        "Ratatouille",
                        "Up",
                        "Despicable Me",
                        "Tangled",
                        "Inside Out",
                        "Wreck It Ralph",
                        "Over the Hedge",
                        "Mulan",
                        "Space Jam",
                        "Hercules",
                        "Tarzan",
                        "Sleeping Beauty",
                        "Star Wars",
                        "Jurassic Park",
                        "The Matrix",
                        "Titanic",
                        "Jaws",
                        "The Shining",
                        "Rocky",
                        "Forrest Gump",
                        "The Godfather",
                        "Jumanji",
                        "Grease",
                        "Footloose",
                        "Twilight",
                        "Gremlins",
                        "Ghostbusters",
                        "Back to the Future",
                        "The Goonies",
                        "The Dark Knight",
                        "Pulp Fiction",
                        "Fight Club",
                        "Inception",
                        "The Avengers",
                        "Gladiator",
                        "The Terminator",
                        "Die Hard",
                        "The Exorcist",
                        "Lilo and Stitch",
                        "Home Alone",
                        "Stuart Little",
                        "Frozen",
                        "Lion King",
                        "The Shawshank Redemption",
                        "The Wizard of Oz",
                        "Top Gun",
                        "Alien",
                        "Avatar",
                        "The Hunger Games",
                        "Black Panther",
                        "The Jungle Book",
                        "Legally Blonde",
                        "Transformers",
                    ],
                },
                tvShows: {
                    name: "TV Shows",
                    words: [
                        "Friends",
                        "Breaking Bad",
                        "Game of Thrones",
                        "The Office",
                        "The Simpsons",
                        "The Walking Dead",
                        "Lost",
                        "Black Mirror",
                        "Sherlock",
                        "Westworld",
                        "House of Cards",
                        "The X Files",
                        "Stranger Things",
                        "Family Guy",
                        "Rick and Morty",
                        "Ozark",
                        "The Vampire Diaries",
                        "Pretty Little Liars",
                        "One Tree Hill",
                        "Friday Night Lights",
                        "American Horror Story",
                        "Modern Family",
                        "South Park",
                        "Tom and Jerry",
                    ],
                },
                tvShowCharacters: {
                    name: "TV Show Characters",
                    words: [
                        "Spongebob Squarepants",
                        "Patrick Star",
                        "Scooby Doo",
                        "Bugs Bunny",
                        "Homer Simpson",
                        "Peter Griffin",
                        "Squidward Tentacles",
                        "Garfield",
                        "Snoopy",
                        "Popeye",
                        "Winnie The Pooh",
                        "Charlie Brown",
                        "Mickey Mouse",
                        "Donald Duck",
                        "Fred Flinstone",
                    ],
                },
                movieCharacters: {
                    name: "Movie Characters",
                    words: [
                        "James Bond",
                        "Indiana Jones",
                        "Luke Skywalker",
                        "Darth Vader",
                        "Harry Potter",
                        "Hermione Granger",
                        "Ron Weasley",
                        "Iron Man",
                        "Captain America",
                        "Black Widow",
                        "Wonder Woman",
                        "Superman",
                        "Batman",
                        "Spider Man",
                        "Buzz Lightyear",
                        "Jack Sparrow",
                    ],
                },
                states: {
                    name: "US States",
                    words: [
                        "Alabama",
                        "Alaska",
                        "Arizona",
                        "Arkansas",
                        "California",
                        "Colorado",
                        "Connecticut",
                        "Delaware",
                        "Florida",
                        "Georgia",
                        "Hawaii",
                        "Idaho",
                        "Illinois",
                        "Indiana",
                        "Iowa",
                        "Kansas",
                        "Kentucky",
                        "Louisiana",
                        "Maine",
                        "Maryland",
                        "Massachusetts",
                        "Michigan",
                        "Minnesota",
                        "Mississippi",
                        "Missouri",
                        "Montana",
                        "Nebraska",
                        "Nevada",
                        "New Hampshire",
                        "New Jersey",
                        "New Mexico",
                        "New York",
                        "North Carolina",
                        "North Dakota",
                        "Ohio",
                        "Oklahoma",
                        "Oregon",
                        "Pennsylvania",
                        "Rhode Island",
                        "South Carolina",
                        "South Dakota",
                        "Tennessee",
                        "Texas",
                        "Utah",
                        "Vermont",
                        "Virginia",
                        "Washington",
                        "West Virginia",
                        "Wisconsin",
                        "Wyoming",
                    ],
                },
                sportsPlayers: {
                    name: "Greatest Athletes of All Time",
                    words: [
                        "Michael Jordan",
                        "Tom Brady",
                        "Serena Williams",
                        "Cristiano Ronaldo",
                        "Lionel Messi",
                        "LeBron James",
                        "Usain Bolt",
                        "Roger Federer",
                        "Muhammad Ali",
                        "Kobe Bryant",
                        "Wayne Gretzky",
                        "Simone Biles",
                        "Tiger Woods",
                        "Babe Ruth",
                        "Michael Phelps",
                        "Steph Curry",
                        "Novak Djokovic",
                        "Rafael Nadal",
                        "Larry Bird",
                        "Magic Johnson",
                        "Usain Bolt",
                        "Usain Bolt",
                    ],
                },
            },
        },
    },
};

export default word_data;
