function writeInsertStatement(data) {
    var insertStatement = "INSERT INTO public.words(name, category_id) VALUES ";
    var length = 0;
    for (let i in data.data.words) {
        length++;
        var name = data.data.words[i]["name"];
        var category_id = data.data.words[i]["category_id"];
        var toBeAdded = `('${name}', ${category_id}), `;
        insertStatement = insertStatement.concat(toBeAdded);
    }
    console.log("Length", length);
    return insertStatement;
}

const data = {
    status: "success",
    results: 126,
    data: {
        words: [
            {
                id: 12,
                name: "Zootopia",
                category_id: 1,
                used: true,
                category_name: "Movies",
            },
            {
                id: 15,
                name: "Little Mermaid",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 16,
                name: "Toy Story",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 17,
                name: "Beauty and the Beast",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 18,
                name: "Aladdin",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 19,
                name: "The Little Rascals",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 20,
                name: "Matilda",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 21,
                name: "Shrek",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 22,
                name: "The Incredibles",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 23,
                name: "Cars",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 24,
                name: "Happy Feet",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 25,
                name: "Ratatouille",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 26,
                name: "Up",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 27,
                name: "Despicable Me",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 28,
                name: "Tangled",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 29,
                name: "Inside Out",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 30,
                name: "Wreck It Ralph",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 31,
                name: "Over the Hedge",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 32,
                name: "Mulan",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 33,
                name: "Space Jam",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 34,
                name: "Hercules",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 35,
                name: "Tarzan",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 36,
                name: "Sleeping Beauty",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 37,
                name: "Star Wars",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 38,
                name: "Jurassic Park",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 39,
                name: "The Matrix",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 40,
                name: "Titanic",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 41,
                name: "Jaws",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 42,
                name: "The Shining",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 43,
                name: "Rocky",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 44,
                name: "Forrest Gump",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 45,
                name: "The Godfather",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 46,
                name: "Jumanji",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 47,
                name: "Grease",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 48,
                name: "Footloose",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 49,
                name: "Twilight",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 50,
                name: "Gremlins",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 51,
                name: "Ghostbusters",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 52,
                name: "Back to the Future",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 53,
                name: "Indiana Jones",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 54,
                name: "Spider Man",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 55,
                name: "The Goonies",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 56,
                name: "The Dark Knight",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 57,
                name: "Pulp Fiction",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 58,
                name: "Fight Club",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 59,
                name: "Inception",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 60,
                name: "The Avengers",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 61,
                name: "Gladiator",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 62,
                name: "The Terminator",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 63,
                name: "Die Hard",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 64,
                name: "The Exorcist",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 10,
                name: "Lilo and Stitch",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 65,
                name: "Home Alone",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 11,
                name: "Stuart Little",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 14,
                name: "Frozen",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 9,
                name: "Lion King",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 66,
                name: "The Shawshank Redemption",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 67,
                name: "The Wizard of Oz",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 68,
                name: "Top Gun",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 69,
                name: "Alien",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 70,
                name: "Avatar",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 71,
                name: "The Hunger Games",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 72,
                name: "Iron Man",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 73,
                name: "Black Panther",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 74,
                name: "The Jungle Book",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 75,
                name: "Legally Blonde",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 76,
                name: "Transformers",
                category_id: 1,
                used: false,
                category_name: "Movies",
            },
            {
                id: 77,
                name: "Friends",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 78,
                name: "Breaking Bad",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 79,
                name: "Game of Thrones",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 80,
                name: "The Office",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 81,
                name: "Stranger Things",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 82,
                name: "The Simpsons",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 83,
                name: "The Walking Dead",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 84,
                name: "Lost",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 85,
                name: "Black Mirror",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 86,
                name: "Sherlock",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 87,
                name: "Westworld",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 88,
                name: "House of Cards",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 89,
                name: "The X Files",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 90,
                name: "Stranger Things",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 91,
                name: "Family Guy",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 92,
                name: "Rick and Morty",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 93,
                name: "Ozark",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 94,
                name: "The Vampire Diaries",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 95,
                name: "Pretty Little Liars",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 96,
                name: "One Tree Hill",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 97,
                name: "Friday Night Lights",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 98,
                name: "American Horror Story",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 99,
                name: "Modern Family",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 100,
                name: "Spongebob Squarepants",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 101,
                name: "Scooby Doo",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 102,
                name: "South Park",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 103,
                name: "Tom and Jerry",
                category_id: 4,
                used: false,
                category_name: "TV Shows",
            },
            {
                id: 104,
                name: "James Bond",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 105,
                name: "Indiana Jones",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 106,
                name: "Luke Skywalker",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 107,
                name: "Darth Vader",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 108,
                name: "Harry Potter",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 109,
                name: "Hermione Granger",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 110,
                name: "Ron Weasley",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 111,
                name: "Iron Man",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 112,
                name: "Captain America",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 113,
                name: "Black Widow",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 114,
                name: "Wonder Woman",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 115,
                name: "Superman",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 116,
                name: "Batman",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 117,
                name: "Spider Man",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 120,
                name: "Buzz Lightyear",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 121,
                name: "Jack Sparrow",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 122,
                name: "Forrest Gump",
                category_id: 3,
                used: false,
                category_name: "Movie Characters",
            },
            {
                id: 123,
                name: "Spongebob Squarepants",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 124,
                name: "Patrick Star",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 125,
                name: "Scooby Doo",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 126,
                name: "Bugs Bunny",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 127,
                name: "Homer Simpson",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 128,
                name: "Peter Griffin",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 129,
                name: "Squidward Tentacles",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 130,
                name: "Garfield",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 131,
                name: "Snoopy",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 132,
                name: "Popeye",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 133,
                name: "Winnie The Pooh",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 134,
                name: "Charlie Brown",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 135,
                name: "Mickey Mouse",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 136,
                name: "Donald Duck",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
            {
                id: 137,
                name: "Fred Flinstone",
                category_id: 2,
                used: false,
                category_name: "TV Characters",
            },
        ],
    },
};

console.log(writeInsertStatement(data));
