export const UPDATE_WORD_PROGRESS = "UPDATE_WORD_PROGRESS";
export const UPDATE_WORD_OF_DAY = "UPDATE_WORD_OF_DAY";
export const UPDATE_WORD_OF_DAY_EMPTY = "UPDATE_WORD_OF_DAY_EMPTY";
export const UPDATE_LOADING_TO_FALSE = "UPDATE_LOADING_TO_FALSE";
export const UPDATE_WORD_OF_DAY_CATEGORY = "UPDATE_WORD_OF_DAY_CATEGORY";
export const UPDATE_WORD_OF_DAY_DATE = "UPDATE_WORD_OF_DAY_DATE";
